name: Build Ghidra 12.1.2 Windows ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - build-win-arm64

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: Ghidra_12.1.2_build

      - name: Setup Java
        run: |
          echo "JAVA_HOME=$env:JAVA_HOME_21_AARCH64" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo $env:JAVA_HOME_21_AARCH64

      - name: Fetch dependencies
        run: gradle -I gradle/support/fetchDependencies.gradle init --no-daemon

      - name: Build Ghidra
        run: gradle buildGhidra -x createJavadocs -x createJsondocs -x createPythonTypeStubs -x createGhidraStubsWheel --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-12.1.2-win-arm64
          path: build/dist/*.zip
